- name: Clone updater repo
  include_tasks: sync_repo.yml

- name: Remove old cron file
  become: true
  ansible.builtin.file:
    dest: /etc/cron.d/system_update_tool.cron
    state: absent

- name: Create scheduled service to update regularly
  become: true
  block:
    - name: Setup timer file to run weekly
      register: update_timer
      ansible.builtin.copy:
        dest: '{{ systemd_folder }}/system-updater.timer'
        content: |
          [Unit]
          Description=Run updates weekly

          [Timer]
          OnCalendar={{ update_job_weekday | title }} *-*-* {{ "%02d" | format(update_job_hour) }}:00:00 {{ update_job_timezone }}
          Persistent=true

          [Install]
          WantedBy=timers.target
    - name: Setup service file
      register: update_service
      ansible.builtin.copy:
        dest: '{{ systemd_folder }}/system-updater.service'
        content: |
          [Unit]
          Description=Run updates

          [Service]
          Type=oneshot
          ExecStart=/root/.local/bin/ansible-playbook {{ update_job_git_repo_path }}/plbk__system_up_to_date.yml
          User=root
    - name: Reload systemd
      when: update_service.changed or update_timer.changed
      ansible.builtin.systemd_service:
        name: system-updater
        daemon_reload: true
    - name: Enable updater timer
      ansible.builtin.systemd_service:
        name: system-updater.timer
        enabled: true
        state: started
- name: Disable unattended upgrades
  block:
    - name: Disable unattended upgrades
      ansible.builtin.systemd_service:
        name: unattended-upgrade
        enabled: false
  rescue:
    - name: Handle error
      ansible.builtin.debug:
        msg: Failed to disable unattended-upgrade, continuing...
